% CNCDril G-Code Output
% Generated by CNCDril Python Version
G21 ; Set units to mm
G90 ; Absolute positioning
G0 Z5.000 ; Move to safe height

% Tool 01 - Ø1.73mm - 77 holes
G0 X0.000 Y0.000
T1 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X5.004 Y17.894 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 2
G0 X5.004 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 3
G0 X5.512 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 4
G0 X5.766 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 5
G0 X6.020 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 6
G0 X5.245 Y18.390 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 7
G0 X4.991 Y18.390 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 8
G0 X5.156 Y15.354 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 9
G0 X8.179 Y16.497 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 10
G0 X8.179 Y16.751 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 11
G0 X8.052 Y17.221 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 12
G0 X8.827 Y17.729 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 13
G0 X9.804 Y17.894 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 14
G0 X10.058 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 15
G0 X10.312 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 16
G0 X10.820 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 17
G0 X10.046 Y18.390 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 18
G0 X9.792 Y18.390 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 19
G0 X8.827 Y16.713 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 20
G0 X9.957 Y15.354 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 21
G0 X12.979 Y16.497 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 22
G0 X12.979 Y16.751 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 23
G0 X12.852 Y17.221 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 24
G0 X13.627 Y17.729 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 25
G0 X14.605 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 26
G0 X14.605 Y17.894 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 27
G0 X14.859 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 28
G0 X15.113 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 29
G0 X15.367 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 30
G0 X15.621 Y17.640 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 31
G0 X14.846 Y18.390 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 32
G0 X14.592 Y18.390 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 33
G0 X13.627 Y16.713 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 34
G0 X14.757 Y15.354 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 35
G0 X17.780 Y16.497 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 36
G0 X17.780 Y16.751 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 37
G0 X17.653 Y17.221 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 38
G0 X18.428 Y17.729 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 39
G0 X18.428 Y16.713 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 40
G0 X18.542 Y11.240 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 41
G0 X18.440 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 42
G0 X18.694 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 43
G0 X18.694 Y8.700 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 44
G0 X18.707 Y8.204 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 45
G0 X18.453 Y8.204 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 46
G0 X17.932 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 47
G0 X17.678 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 48
G0 X15.646 Y9.373 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 49
G0 X15.519 Y9.843 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 50
G0 X15.519 Y10.097 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 51
G0 X14.872 Y9.119 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 52
G0 X14.872 Y8.865 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 53
G0 X13.894 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 54
G0 X13.894 Y8.700 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 55
G0 X13.653 Y8.204 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 56
G0 X13.386 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 57
G0 X13.132 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 58
G0 X10.846 Y9.373 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 59
G0 X10.719 Y9.843 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 60
G0 X10.719 Y10.097 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 61
G0 X10.071 Y9.119 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 62
G0 X10.071 Y8.865 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 63
G0 X9.093 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 64
G0 X8.839 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 65
G0 X8.585 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 66
G0 X8.331 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 67
G0 X8.077 Y8.954 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 68
G0 X9.093 Y8.700 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 69
G0 X9.106 Y8.204 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 70
G0 X8.852 Y8.204 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 71
G0 X8.941 Y11.240 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 72
G0 X5.918 Y10.097 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 73
G0 X5.918 Y9.843 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 74
G0 X6.045 Y9.373 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 75
G0 X5.271 Y9.119 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 76
G0 X5.271 Y8.865 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 77
G0 X13.741 Y11.240 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Tool 02 - Ø2.54mm - 9 holes
G0 X0.000 Y0.000
T2 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X14.834 Y6.033 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 2
G0 X16.129 Y6.033 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 3
G0 X19.685 Y8.992 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 4
G0 X19.685 Y10.287 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 5
G0 X16.002 Y20.561 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 6
G0 X7.595 Y20.561 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 7
G0 X4.001 Y10.287 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 8
G0 X4.001 Y8.992 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 9
G0 X7.595 Y6.033 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Tool 03 - Ø3.20mm - 7 holes
G0 X0.000 Y0.000
T3 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X11.849 Y13.145 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 2
G0 X19.050 Y13.145 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 3
G0 X20.828 Y4.051 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 4
G0 X4.648 Y6.680 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 5
G0 X2.896 Y4.051 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 6
G0 X4.648 Y19.799 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 7
G0 X20.828 Y22.593 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Tool 04 - Ø4.20mm - 1 holes
G0 X0.000 Y0.000
T4 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X2.500 Y2.500 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Tool 05 - Ø5.08mm - 5 holes
G0 X0.000 Y0.000
T5 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X4.877 Y13.043 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 2
G0 X9.220 Y13.043 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 3
G0 X7.048 Y6.909 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 4
G0 X16.650 Y6.909 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 5
G0 X7.048 Y19.685 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Tool 06 - Ø5.38mm - 1 holes
G0 X0.000 Y0.000
T6 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X11.862 Y2.027 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Tool 07 - Ø10.16mm - 2 holes
G0 X0.000 Y0.000
T7 M6 ; Tool change
S1000 M3 ; Spindle on

% Hole 1
G0 X11.862 Y4.940 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

% Hole 2
G0 X11.862 Y3.670 ; Move to hole
G1 Z-2.000 F50 ; Drill
G0 Z5.000 ; Retract

M5 ; Spindle off
G0 X0 Y0 ; Move to origin
M30 ; End of program